### ISSUE TITLE
F1 scores of pedestrian and car

### ISSUE THREAD

**Issue by DaZhUUU** [tudelft-iv/RTCnet#13]
In your experiment, the F1 score of car is lower than pedestrian and why is this?

I think the car should be classified easily because of the larger body and the metal surface that results in the strong RCS. 

Maybe there are some ghost targets around the car, the radar data of all cars should be similar.

And does the problem only appear in your research? Or are others' the same?

Thanks!

**Comment by andraspalffy** [comment]
Hello,

my apologies, I missed this issue.
You are right that usually, cars are somewhat easier to detect with radars because of their size.

This paper is about a classify-then-cluster approach, which means that each target is classified **individually**. 
That is, size does not matter, only the speed distribution in the very close region around the target.

Since cars have rigid bodies, this speed distribution is rather "boring" for cars, and thus, the car-related radar points are harder to classify on their own. Pedestrians and cyclists have very interesting speed distributions, which are easier to recognize.

I hope this helps. Andras
