### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Nick-Sun1018** [tudelft-iv/RTCnet#16]
I'm appreciate your excellent work, would you please release pretrained models for testing, thank you!

**Comment by andraspalffy** [comment]
Hi Nick, unfortunately neither the data, nor the models trained on them can be shared because of NDAs between the university and the radar manufacturer.

On the other hand you probably could not use them anyway, as they are highly sensor specific, i.e. resolution, format, params should have matched your data.

If you have your own data, I suggest to do some dirty annotations on it and train your own networks, will be much more efficient.

**Comment by Nick-Sun1018** [comment]
Thanks for your reply! 
I'm working on the fusion of camera and radar, and confused by the manufacturer and corresponding products, could you please give me some advice, I'll be very appreciated !

**Comment by andraspalffy** [comment]
Hey Nick, send me a mail about your questions and happy to discuss it!
apalffy AT tudelft.nl
